site_name: Mohamed Martini — Resume
site_url: https://mhdmartini.github.io/resume/

nav:
- README.md

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Inter
    code: Roboto Mono
  features:
  - navigation.footer
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

markdown_extensions:
- attr_list
- md_in_html
- def_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ""
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ""

plugins: []

extra:
  generator: false
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/mohamed-martini/
    name: LinkedIn
  - icon: fontawesome/brands/github
    link: https://github.com/MhdMartini
    name: GitHub
  - icon: material/email
    name: mhdmart1@gmail.com
    link: mailto:mhdmart1@gmail.com
  - icon: material/web
    name: leverai.tech
    link: https://leverai.tech

extra_css:
- stylesheets/extra.css

extra_javascript:
- javascripts/custom.js
