[project]
name = "resume"
version = "2026.4.7"
description = "Resume webpage"
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
[[project.authors]]
name = "Mohamed Martini"
email = "mhdmart1@gmail.com"

[dependency-groups]
docs = ["mkdocs>=1.6.1", "mkdocs-material>=9.6.5"]

[project.license]
text = "MIT"

[tool.pdm]
distribution = false
