name: ci-docs
description: Builds project documentation with mkdocs.

on:
  workflow_call:
    inputs:
      version:
        description: 'docs version'
        type: string
        required: true
      dry-run:
        type: boolean
        required: false
        default: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: pdm-project/setup-pdm@v4.2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pdm sync -dG docs --skip=:all

    - run: pdm run mkdocs build

    - name: publish website
      if: inputs.dry-run == false
      run: |
        echo ${{ inputs.version }}
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        pdm run mike deploy ${{ inputs.version }} --push
