name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  pages: write

env:
  COLUMNS: 120

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      year: ${{ steps.date.outputs.year }}
      month: ${{ steps.date.outputs.month }}
      day: ${{ steps.date.outputs.day }}
      date: ${{ steps.date.outputs.date }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: |
          today=$(date +'%Y.%m.%d')
          year=$(date +'%Y')
          month=$(date +'%m')
          day=$(date +'%d')
          echo "::set-output name=year::$year"
          echo "::set-output name=month::$month"
          echo "::set-output name=day::$day"
          echo "::set-output name=date::$today"
          
      - name: Output version details
        run: |
          echo "Year: ${{ steps.date.outputs.year }}"
          echo "Month: ${{ steps.date.outputs.month }}"
          echo "Day: ${{ steps.date.outputs.day }}"
          echo "Date: ${{ steps.date.outputs.date }}"

  release-dry-run:
    needs: [get-date]
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit
    with:
      version: ${{ needs.get-date.outputs.date }}
      dry-run: true

  build-docs:
    needs: [get-date]
    uses: ./.github/workflows/ci-docs.yml
    secrets: inherit
    with:
      version: ${{ needs.get-date.outputs.year }}
      dry-run: true

  check:
    if: always()
    outputs:
      result: ${{ steps.all-green.outputs.result }}
    needs:
      - release-dry-run
      - build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  release:
    needs: [get-date, check]
    if: needs.check.outputs.result == 'success' && github.ref_name == 'main'
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit
    with:
      version: ${{ needs.get-date.outputs.date }}

  publish-docs:
    needs: [get-date, check]
    uses: ./.github/workflows/ci-docs.yml
    secrets: inherit
    with:
      version: ${{ needs.get-date.outputs.year }}
