name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  pages: write

env:
  COLUMNS: 120

jobs:

  release-dry-run:
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit
    with:
      dry-run: true

  build-docs:
    needs: [release-dry-run]
    uses: ./.github/workflows/ci-docs.yml
    secrets: inherit
    with:
      version: ${{ needs.release-dry-run.outputs.year }}

  check:  # This job does nothing and is only used for the branch protection
    if: always()
    outputs:
      result: ${{ steps.all-green.outputs.result }}
    needs:
      - build-docs
      - release-dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}

  release:
    needs: [check]
    if: needs.check.outputs.result == 'success' && github.ref_name == 'main'
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit
    with: 
      dry-run: false
